services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: gaming_leaderboard_app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "3000:3000"
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_USERNAME=${REDIS_USERNAME}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    networks:
      - gaming_network

  bot1:
    build:
      context: ./bot
      dockerfile: Dockerfile
    container_name: gaming_bot_1
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_USERNAME=${REDIS_USERNAME}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - BOT_NAME=Phoenix
    networks:
      - gaming_network

  bot2:
    build:
      context: ./bot
      dockerfile: Dockerfile
    container_name: gaming_bot_2
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_USERNAME=${REDIS_USERNAME}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - BOT_NAME=Dragon
    networks:
      - gaming_network

  bot3:
    build:
      context: ./bot
      dockerfile: Dockerfile
    container_name: gaming_bot_3
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_USERNAME=${REDIS_USERNAME}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - BOT_NAME=Shadow
    networks:
      - gaming_network

networks:
  gaming_network:
    driver: bridge